main:
  web_trigger_deploy:
    - build-backend-image:
      services:
        - docker
      stages:
        - name: docker build
          script:
            - docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}-backend:${CNB_COMMIT} ./backend/Dockerfile
        - name: docker push
          script:
            - docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}-backend:${CNB_COMMIT}
    - build-frontend-image:
      services:
        - docker
      stages:
        - name: docker build
          script:
            - docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}-frontend:${CNB_COMMIT} ./frontend/Dockerfile
        - name: docker push
          script:
            - docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}-frontend:${CNB_COMMIT}