main:
  web_trigger_deploy:
    - build-backend-image:
      services:
        - docker
      stages:
        - name: set backend tag
          script: echo -n "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/backend:latest"
          exports:
            info: IMAGE_TAG
        - name: docker build
          script:
            - docker build -t $IMAGE_TAG ./backend
        - name: docker push
          script:
            - docker push $IMAGE_TAG
    - build-frontend-image:
      services:
        - docker
      stages:
        - name: set backend tag
          script: echo -n "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/frontend:latest"
          exports:
            info: IMAGE_TAG
        - name: docker build
          script:
            - docker build -t $IMAGE_TAG ./backend
        - name: docker push
          script:
            - docker push $IMAGE_TAG