server:
  port: 8080

logging:
  level:
    root: info
    web: debug

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost,https://localhost,http://localhost:8080,http://localhost:5173}
  allowed-methods: ${CORS_ALLOWED_METHODS:*}
  allowed-headers: ${CORS_ALLOWED_HEADERS:*}
  allowed-expose-headers: ${CORS_ALLOWED_EXPOSE_HEADERS:*}
